# Generated by Django 4.2.7 on 2023-12-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
