# Generated by Django 4.2.7 on 2023-12-15 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_counted_views_post_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created_date",
        ),
    ]
